### ISSUE TITLE
Wrong return type

### ISSUE THREAD

**Issue by aurquijo8** [gam04/estafeta-command#1]
When we try to find a suburb by name but it doesn't exist we get wrong return type. The function "first" should return a "LocationSection" object but "reset" function give us "false" when the array is empty.

It is possible to check if it is empty before getting the first element but it would be nice if "first" function could trow "SuburbNotFoundExeption" exception or something.

**Comment by gam04** [comment]
Hi @arlequin99 .
Thanks for this observation.

It´s fixed in f83d3eb8a16f47d620ec4eb9593bf5a15743e475 . Please, update to `1.0.2`
